Regenerate the lock file
Notice a sporadic failure, first observed a few commits ago:

Randomized with seed 05144
Started
no user for token InvalidToken
.no user for token undefined
..undefined
.no user in Promise for token ValidToken
...The request origin https://not.allowed is not allowed.
.F..No function named BadName.
..undefined
..

Failures:
1) Server CORS allows to pass custom CORS headers
  Message:
    TypeError: fetch failed
  Stack:
    Caused by: SocketError: other side closed
    error properties: Object({ code: 'UND_ERR_SOCKET', socket: Object({ localAddress: '::1', localPort: 54868, remoteAddress: undefined, remotePort: undefined, remoteFamily: undefined, timeout: undefined, bytesWritten: 447, bytesRead: 131 }) })
        at Socket.onHttpSocketEnd (node:internal/deps/undici/undici:7700:26)
        at Socket.emit (node:events:520:35)
        at endReadableNT (node:internal/streams/readable:1729:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:90:21)

15 specs, 1 failure
Finished in 0.077 seconds
Randomized with seed 05144 (jasmine --random=true --seed=05144)